services:
  rabbitmq:
    image: rabbitmq:4.2-alpine
    restart: unless-stopped
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 6s
    expose:
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - broker

volumes:
  rabbitmq-lib:
  rabbitmq-log:

networks:
  broker:
    driver: bridge