name: gravitalia

include:
  - path: cloudflared.yaml
  - path: proxy.yaml
  - path: account.yaml
  - path: news.yaml
  - path: turms.yaml
  - path: database.yaml
  - path: broker.yaml
  - path: telemetry.yaml