services:
  postgres:
    image: postgres:18.1
    container_name: postgres
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../config/db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql
    networks:
      - database

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=master_key
      - MEILI_NO_ANALYTICS=true
      - MEILI_DB_PATH=/data.ms
    expose:
      - 7700
    volumes:
      - meili-data:/data.ms
    networks:
      - database

  memcached:
    image: memcached:1.6
    container_name: memcached
    expose:
      - 11211
    networks:
      - database

volumes:
  postgres-data:
  meili-data:

networks:
  database:
    driver: bridge