services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1-alpine
    expose:
      - 80
    volumes:
      - ../config/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ../config/proxy/cloudflare-ips.conf:/etc/nginx/cloudflare-ips.conf
    networks:
      - proxy

networks:
  proxy:
    driver: bridge