services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    depends_on:
      - prometheus
      - loki
      - jaeger
    expose:
      - 3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana/provisioning/datasources
    networks:
      - telemetry

  prometheus:
    image: prom/prometheus:v3.6.0
    restart: unless-stopped
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    expose:
      - 9090
    volumes:
      - ../config/telemetry/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    networks:
      - telemetry

  loki:
    image: grafana/loki:3.5
    restart: unless-stopped
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - promtail
    expose:
      - 3100
    volumes:
      - ../config/telemetry/loki.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - telemetry

  promtail:
    image: grafana/promtail:3.5
    restart: unless-stopped
    container_name: promtail
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - /var/log:/var/log
      - ../config/telemetry/promtail.yaml:/etc/promtail/config.yaml
    networks:
      - telemetry

  jaeger:
    image: jaegertracing/all-in-one:1.73.0
    restart: unless-stopped
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    expose:
      - 16686
      - 14268
      - 14250
      - 9411
    networks:
      - telemetry

  otel-collector:
    image: otel/opentelemetry-collector:0.136.0
    restart: unless-stopped
    container_name: otel
    command: --config=/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
      - loki
      - prometheus
    expose:
      - 1888
      - 8888
      - 8889
      - 13133
      - 4317
      - 55679
    volumes:
      - ../config/telemetry/otel.yaml:/etc/otel-collector-config.yaml
    networks:
      - telemetry

volumes:
  grafana-conf:
  grafana-data:
  prometheus-data:
  loki-data:

networks:
  telemetry:
    driver: bridge